security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm:           sha1
            encode_as_base64:    false
            iterations:          1

    access_decision_manager:
    # Strategy can be: affirmative, unanimous or consensus
        strategy: consensus
        
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            context: user
            form_login:
                provider: fos_userbundle
                use_referer: true
                always_use_default_target_path: false
                default_target_path: /admin/dashboard
            #    failure_handler: admin_failure_handler
                failure_path:    /login
                failure_forward: false
                remember_me:    true
                require_previous_session: true

            remember_me:
                key:      "%secret%"
                lifetime: 3600
                domain:   ~
                always_remember_me: true
                remember_me_parameter: _remember_me

            anonymous:    true
            logout:
                path: fos_user_security_logout
                target: /login

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_USER }
        - { path: ^/efconnect, role: ROLE_USER }
        - { path: ^/elfinder, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
            
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER